name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82e46c3c9aefc988f7da5b562d10a466c00a05f2bbf3aee57556aa1084b25a5e"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
