name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5d21beebf0c9dc38752c41b883945402481fc211c79369376de930267958817"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
