name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce75618f66c054e7ca01ae0a5efba3bb2c5665cb2a50e5a6de7b7de59c978209"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
