name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05fd16f87f88bff2481991c9b9bd3baa831b3da21defac9b8939814392d827ac"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
