name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07c97ad835c26d9f317884624b5e3dcbecb316982323605e08fa509d1a5f35fd"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
