name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "135671c3fab6c96b43e12f1c95a1c414980f4b00ef1e5b1521537800545f4cd2"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
