name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b513104a93278cfe2d4ce85100d44b73215007c3700475e2b860c9b7f84a3c0"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.0"
