name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa8112eccb87f6219ac9c959fe48e7bf7e09619f04c4f3f28a8bfa3cf258a4d5"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
