name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3042ed06e89d4862a7c6ab2fc6d8a70de34e829700c765c045a8da55d44c0e06"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
