name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5291918030496589014557b68e695c6450a4fa2eeacb35e822ffc6792e402cf4"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
