name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b744e63ef48ec77eb87014dc0a6a8cfe80a54eb9aa3ff1a75d3884a56c8048b4"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
