name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04965b4e57037ed0024d1305e183e33ba4ff63d0c5de0d10cce52045b1bb4e10"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
