name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b91a344dd0080f0b46e49d97bc124c225832d536b4602a6a33d530b68940b7f"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.0"
