name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398b3f0a0b3cdbf6a16f27175daf7372883ae825fe5181ff753f7a3eef653b33"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
