name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12dcd25d81edaa60b6435a5f7b21ea59c4a1b40200c532d3b4b5c8df5cd89b7c"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
