name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d2726b9cc739ab414a30e7859d3445f702433024c899d73b98bd7d020649ab"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
