name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a771422f008b1860ee9c6fcc3355a01021d3ec99d47f9158441b9ccaa0e46ae4"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
