name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d9f423424fb23a96ae6b044c21c8fdfbc3ce03dac8240184a0eca126d4336c9"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
