name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01c4bd88b50838ff34f7a504e25e20d3ca0128afa174a484d975d482e09768b"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
