name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10453a98a0ea65874417ce39e92054416084cf5b3f6a9362ccd7e2796018da19"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
