name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88d68ad9fa6767142a65d7e319e76caa2ba96f6b8c6679c0e214198d11506311"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
