name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "679ebaa84a4bdd3af78b8977d109ffc52c61d7879b238fac79f9837d3a1527af"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
