name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a4e3fee43c723a3b479eb59db9cd908807b18586f0f8c909df256446fb179c"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
