name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6e8cc4e87ada3fc3dce591c7268a97da1ffd0d8ba5bbbb2eaf1746452786d5a"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.0"
