name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, emorydeer2"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee368674144a1f1cac8f70d17da3fd6005246130de5b0557b2e36ee9a75d0fb4"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
