name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "170f033171c3baa2c1f15897c03fb2e45b46f343403598db2e95a2355997220f"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
