name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d3fdd3826ac02a3080001f4705b8269a2c7a47cbbc282945c866e1c56b011ff"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
