name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b4d541a2e6b88f4aaccb41f5979fe1e314f0920cd3d0d52164acd3b7ed2f7d1"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.0"
