name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de3ec950cca309e7e47bbbd3b4d1baa699b71fb376b6136b5967262153436be9"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
