name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1adb5f2bcb5823d89ccc8e271a834008020561a09473bddffba22b414a7acc8"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
