name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9c5d14ad782812b07f4e1f45ab89f10b2ee01ab04fd2c119cd230b9ef5b7fec"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
