name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63d7e4e684822e9762ddc55ec1636a728928435c581f9631ac5842517e649a58"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
unsup = "0.2.0"
