name = "Pseudoscience Modpack Iteration 1"
author = "oskardotglobal, khaoslatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2984896e88476f5744ed93fed83d0492a91f354d6cee26c5dab4346f6a2ce95"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
