
#Friends
[friends]
	#A list of users who can be chosen when it spawns a distant friend
	friends = ["KhaosLatet", "PixelAgent007", "Brickbattle", "EeeLee", "Not_Mafia_Boss", "Dinnerbone", "Grumm", "Notch", "jeb_", "Quas4r_", "joshpd8318", "CrimsonDazeTB", "Damian_Kirishima", "Zink_bot", "KRUT324", "Brickbattle", "Alganom"]
	#Add the players from the whitelist to the Friends list [default: true]
	addWhitelistPlayers = true

#Compat
[compat]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = false
	#The player mobs Name Links
	playerMobsWhitelist = [""]

