#Whether players should be able to set their spawn at beds.
#This has no effect on whether players can sleep or not. Only disallows setting spawn at beds.
#MAKE SURE TO REMOVE '#minecraft:beds' FROM 'bannedRespawnBlocks'!
allowBedRespawning = false
#A list of blocks that players cannot respawn from. This is mainly to enforce 'allowBedRespawning'.
#Keep in mind that adding modded blocks to this list will not prevent the player from 'setting' their spawn at that block.
#It will only prevent them from spawning their when respawning.
#Tags are supported. To use them, use a hashtag before the name. Eg. #minecraft:beds
bannedRespawnBlocks = ["#minecraft:beds"]

[immortalityCurse]
	#Whether the curse of immortality should be enabled or not.
	enableCurse = true
	#Sound to play when respawning with the immortality curse.
	curseSound = "minecraft:entity.elder_guardian.curse"
	#Max level of the immortality curse.
	#The player will be sent to world spawn the death after getting the max level.
	curseMaxLevel = 5
	#How much each death should increment the immortality curse by.
	curseLevelIncrement = 1
	#How long the immortality curse should last after respawning. (In ticks)
	curseDuration = 6000

[charge]
	#The items used for charging an obelisk.
	#Syntax: ["<ITEM_ID>|<CHARGE_AMOUNT>", ...]
	#Ex:     ["minecraft:stick|35"]
	obeliskChargeItems = ["minecraft:ender_eye|25", "minecraft:ender_pearl|10"]
	#Sound to play when charging an obelisk.
	obeliskChargeSound = "minecraft:block.respawn_anchor.charge"
	#Sound to play when de-charging(negative charge value) or respawning at an obelisk.
	obeliskDepleteSound = "minecraft:block.respawn_anchor.deplete"
	#Sound to play when setting your spawn at an obelisk.
	obeliskSetSpawnSound = "minecraft:block.respawn_anchor.set_spawn"
	#How much charge (%) should be consumed when respawning at an obelisk.
	obeliskDepleteAmount = 20
	#Block placed under an obelisk to allow for infinite charge.
	infiniteChargeBlock = "create_dd:stargaze_singularity_block"
	#Whether players can set their spawn at obelisks without charge.
	allowEmptySpawnSetting = false

[teleport]
	#Whether players can teleport to obelisks by binding a recovery compass to a lodestone under the obelisk.
	enableTeleportation = false
	#The delay before being able to teleport again. (In ticks)
	#Keep this above 100, otherwise issues will arise.
	#Default value: 3 minutes/3600 ticks
	teleportationCooldown = 3600
	#The delay before being able to teleport again after an unsuccessful teleport. (Eg. player moves or switches items, etc.
	teleportationBackupCooldown = 200
	#Whether players drop their items when teleporting. If enabled, all enabled perks in the 'perks' section will apply.
	dropItemsOnTeleport = false
	#Whether players drop their recovery compass when teleporting.
	dropCompassOnTp = true
	#The amount of experience(points, not levels) consumed when teleporting to an obelisk.
	#Useful numbers: https://minecraft.fandom.com/wiki/Experience#Leveling_up (See 'Total XP')
	#Default value: 27 points/3 levels
	xpCost = 27
	#The amount of experience(levels, not points) consumed when teleporting to an obelisk.
	#This is different to 'xpCost' as the cost to teleport will technically get more expensive the more levels you have.
	#This is similar to how Waystones works.
	levelCost = 0
	#Whether players can teleport whilst having the immortality curse.
	allowCursedTeleportation = false
	#Whether the immortality curse should be forcefully applied when teleporting.
	#Regardless of this value, you will still receive the curse when teleporting to uncharged obelisks.
	forcedCurseOnTp = false
	#Minimum charge required to teleport. Values of 0 or lower will disable this requirement.
	minimumTpCharge = 1.0
	#Amount of charge lost when teleporting to an obelisk.
	teleportationChargeCost = 20.0

[revive]
	#Whether entity revival via respawn obelisk should be enabled.
	enableRevival = true
	#Item used to revive an obelisk's saved entities.
	revivalItem = "minecraft:totem_of_undying"
	#Max number of entities that can be revived at once.
	maxRevivalEntities = 3
	#Whitelist for all entities that can be revived. (Tags are supported)
	#Any entry beginning with '$' is a hardcoded option that allows for the respective type to pass through.
	#Available '$'s:
	#'$tamables' (any tamable entity),
	#'$animals' (pigs, cows, sheep, etc.),
	#'$merchants' (villagers)
	revivableEntities = ["$tamables", "$animals", "$merchants"]
	#Whether the revivable entities list should act as a blacklist.
	revivableEntitiesBlacklist = false
	#Obelisk depletion amount when reviving entities.
	revivalCost = 10.0

[trustedPlayers]
	#Whether players can be trusted/banned from accessing certain obelisks.
	enablePlayerTrust = true
	#Whether untrusted players can break the obelisk.
	allowObeliskBreaking = true
	#Whether untrusted players can respawn at the obelisk.
	allowObeliskRespawning = true
	#Whether untrusted players can interact with the obelisk.
	allowObeliskInteraction = true

[cores]
	#Max number of revive entities that a core can hold.
	#I recommend keeping this at a low amount, as large amounts (>10? Haven't tested values greater.) can cause issues with data storage.
	maxStoredEntities = 5
	#The maximum amount of 'max charge' an obelisk can have. (Cores can be upgraded in order to reach this amount, but cannot go over.)
	maxMaxCharge = 1000
	#The default core inside wild obelisks. (Addons can easily create new cores, this is used for that.)
	defaultCore = "respawnobelisks:obelisk_core"
	#The chance for wild obelisks to have a core. (in %)
	wildCoreChance = 100.0
	#The minimum amount of charge (%) a wild obelisk will spawn with. (inclusive)
	wildMinCharge = 100
	#The maximum amount of charge (%) a wild obelisk will spawn with. (exclusive, in %)
	wildMaxCharge = 101
	#The minimum amount of max charge a wild obelisk will spawn with. (inclusive)
	wildMinMaxCharge = 100
	#The maximum amount of max charge a wild obelisk will spawn with. (exclusive)
	wildMaxMaxCharge = 101

[perks]
	#Minimum charge required to keep items on death when respawning at obelisks. Negative (or 0) amounts will disable this requirement.
	minKeepItemCharge = 1.0
	#Whether players can keep items on death even when they have the immortality curse.
	allowCursedItemKeeping = false

	[perks.keepInv]
		#Whether you should keep your inventory (discluding armor and offhand) when respawning at an obelisk.
		keepInventory = false
		#The chance (%) to keep each item in your inventory.
		keepInventoryChance = 100.0

	[perks.keepHotbar]
		#Whether you should keep your hotbar when respawning at an obelisk.
		keepHotbar = false
		#The chance (%) to keep each item in your hotbar.
		keepHotbarChance = 100.0

	[perks.keepArmor]
		#Whether you should keep your armor when respawning at an obelisk.
		keepArmor = false
		#The chance (%) to keep each armor piece.
		keepArmorChance = 100.0

	[perks.keepOffhand]
		#Whether you should keep your offhand item when respawning at an obelisk.
		keepOffhand = false
		#The chance (%) to keep the item in your offhand.
		keepOffhandChance = 100.0

	[perks.keepExperience]
		#Whether you should keep experience after death when respawning at an obelisk.
		keepExperience = false
		#How much (%) experience should be kept when respawning at an obelisk.
		keepExperiencePercent = 100.0

	[perks.keepTrinkets]
		#Whether you should keep your curios/trinkets (if installed) when respawning at an obelisk.
		keepTrinkets = false
		#The chance (%) to keep each trinket in your trinket inventory.
		keepTrinketsChance = 100.0

	[perks.obeliskbound]
		#Whether the obeliskbound enchantment should be enabled.
		enableEnchantment = true
		#Whether the obeliskbound enchantment should be treasure only. (Can't find in enchantment table)
		treasureOnly = true
		#Whether the obeliskbound enchantment can be found in villager trades.
		tradeable = false
		#Whether the obeliskbound enchantment can be discoverable. (Found throughout chests in world)
		discoverable = true
		#The chance (%) per level to keep items with the obeliskbound enchantment.
		chancePerLevel = 25.0
		#The highest level the obeliskbound enchantment can have.
		maxLevel = 3

